// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfCXfAnfP9Kn3LYydD_hotvq7zmyxTveY',
    appId: '1:88506512347:android:236ed64fa1bb59a1f2adfe',
    messagingSenderId: '88506512347',
    projectId: 'le-john-mindfulness',
    storageBucket: 'le-john-mindfulness.firebasestorage.app',
    databaseURL: 'https://le-john-mindfulness-default-rtdb.firebaseio.com',
  );
}
